name: yyu_library
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  shimmer: ^2.0.0
  get: ^4.6.6
  slide_to_act: ^2.0.2
  firebase_auth: ^4.11.0
  flutter_staggered_grid_view: ^0.7.0
  marquee: ^2.2.3
  firebase_storage: ^11.4.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  widget_circular_animator: ^1.0.0
  google_nav_bar: ^5.0.6
  flutter_staggered_animations: ^1.1.1
  floating_menu_panel: ^0.0.2
  barcode_scan2: ^4.3.0
  awesome_dialog: ^3.1.0
  cached_network_image: ^3.3.0
  flip_panel_plus: ^1.0.0+3
  nfc_manager: ^3.3.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/books/
    - assets/authors/


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Baumans
      fonts:
        - asset: assets/fonts/Baumans-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
