// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDynNVgr5pb1GjQjGyYX60eBIcsoTHjq0A',
    appId: '1:240962614855:web:11e0e4ab626abbdf51e362',
    messagingSenderId: '240962614855',
    projectId: 'yyu-library',
    authDomain: 'yyu-library.firebaseapp.com',
    storageBucket: 'yyu-library.appspot.com',
    measurementId: 'G-LZKX9ND1JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCncuqqmWbWDSo7fHU3RKKM7OUmnUzf0TE',
    appId: '1:240962614855:android:40b109c103eff61651e362',
    messagingSenderId: '240962614855',
    projectId: 'yyu-library',
    storageBucket: 'yyu-library.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIV46L8vtrFJtVkDCCBS-2A3TcLMBt8rg',
    appId: '1:240962614855:ios:f09d344aff90000751e362',
    messagingSenderId: '240962614855',
    projectId: 'yyu-library',
    storageBucket: 'yyu-library.appspot.com',
    iosBundleId: 'com.yyu.library.yyuLibrary',
  );
}
